apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: controller-role
rules:
  - apiGroups:
    - ""
    resources:
      - "namespaces"
    verbs:
      - create
      - get
      - list
      - delete
      - update
      - patch
  - apiGroups:
      - ""
    resources:
      - "pods"
    verbs:
      - create
      - get
      - list
      - delete
      - update
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: controller-rolebinding
subjects:
  - kind: ServiceAccount
    name: podinstanciater
    namespace: system
roleRef:
  kind: Role
  name: controller-role
  apiGroup: rbac.authorization.k8s.io
