# permissions for end users to edit podinstanciators.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: podinstanciator-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: podinstanciater
    app.kubernetes.io/part-of: podinstanciater
    app.kubernetes.io/managed-by: kustomize
  name: podinstanciator-editor-role
rules:
- apiGroups:
  - api.my.domain
  resources:
  - podinstanciators
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - api.my.domain
  resources:
  - podinstanciators/status
  verbs:
  - get
